---
- hosts: all

  vars_files:
    - config/main.yml

  pre_tasks:
    - stat: path=config/local.yml
      register: local_config_file
    - include_vars: config/local.yml
      when: local_config_file.stat.exists
    - set_fact:
        homebrew_taps: "{{ brew_taps }} + {{ extra_brew_taps|default([]) }}"
        homebrew_installed_packages: "{{ brew_packages }} + {{ extra_brew_packages|default([]) }}"
        homebrew_cask_apps: "{{ cask_apps }} + {{ extra_cask_apps|default([]) }}"
        mas_installed_apps: "{{ mas_apps }} + {{ extra_mas_apps|default([]) }}"
        atom_packages_packages: "{{ atom_packages }} + {{ extra_atom_packages|default([]) }}"

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas
    - role: hnakamur.atom-packages

  tasks:
    - import_tasks: tasks/bash.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/ruby.yml

    - name: Install MacOS Updates
      command: softwareupdate -i -a
      become: yes

    - name: Install Requiem executable
      file:
        src: "{{ playbook_dir }}/script/requiem"
        dest: /usr/local/bin/requiem
        state: link
      become: true
