---
- stat: path=/usr/local/bin/bash
  register: brew_bash

- name: Add Homebrew bash to list of shells
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/bash
  become: yes
  when: brew_bash.stat.exists

- name: Ensure user is setup
  user:
    name: mloberg
    shell: /usr/local/bin/bash
    generate_ssh_key: yes
  become: yes
  when: brew_bash.stat.exists

- name: Clone Bash-it
  git:
    repo: 'https://github.com/Bash-it/bash-it.git'
    depth: 1
    dest: "~/.bash_it"

- name: Install Bash-it
  command: "~/.bash_it/install.sh --silent --no-modify-config"

- name: Enable Bash-it aliases
  file:
    src: "~/.bash_it/aliases/available/{{ item }}.aliases.bash"
    dest: "~/.bash_it/aliases/enabled/{{ item }}.aliases.bash"
    state: link
  with_items: "{{ bash_it_aliases }}"

- name: Enable Bash-it completions
  file:
    src: "~/.bash_it/completion/available/{{ item }}.completion.bash"
    dest: "~/.bash_it/completion/enabled/{{ item }}.completion.bash"
    state: link
  with_items: "{{ bash_it_completions }}"

- name: Enable Bash-it plugins
  file:
    src: "~/.bash_it/plugins/available/{{ item }}.plugin.bash"
    dest: "~/.bash_it/plugins/enabled/{{ item }}.plugin.bash"
    state: link
  with_items: "{{ bash_it_plugins }}"

- name: Create ~/.bash.d for loading bash_profile
  file:
    path: ~/.bash.d
    state: directory
