---
git_name: Matt Loberg
git_email: loberg.matt@gmail.com

extra_brew_taps: []
extra_brew_packages: []
extra_cask_apps:
  - hipchat

extra_mas_apps:
  - { name: "Affinity Photo", id: 824183456 }

extra_atom_packages: []

extra_ruby_versions: []
extra_default_gems: []

extra_php_versions: []
